apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentapp
  labels:
    app: deploymentapp
spec:
  replicas: 1  # Desired number of pods
  selector:
    matchLabels:
      app: deploymentapp
  template:
    metadata:
      labels:
        app: deploymentapp
    spec:
      containers:
      - name: ubuntu-container
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "while true; do echo hello world; sleep 10; done"]  # Dummy command to keep the container running
        resources:
          requests:    # Minimum resource requests
            cpu: "100m"
            memory: "128Mi"
          limits:      # Maximum resource limits
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 80  # Example port (not used here, but you can modify as needed)

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa1
  labels:
    app: hpa1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploymentapp  # Reference to the deployment
  minReplicas: 1  # Minimum number of pods
  maxReplicas: 5  # Maximum number of pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Scale if CPU utilization is above 50%