apiVersion: v1
kind: Pod
metadata: 
  name: mystudentapp
  namespace: mystudentnamespace
  labels:
    app: mystudentapp
spec: 
  containers: 
    - name: student
      image: aamantamboli/student
      ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: my-service2
  namespace: mystudentnamespace
spec:
  type: LoadBalancer
  selector:
    app: mystudentapp 
  ports:  
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: student
