apiVersion: v1
kind:  ReplicationController
metadata: 
       name: apprc
       labels:
            app: apprc
spec: 
    replicas: 3  #it will made as per nodes 
    template:
      metadata:  #like a tag
         labels: 
            app: apprc
      spec:
        containers:
            - name: mypod-cont1
              image: nginx:latest
              resources: 
                  requests:
                    cpu: "50m"
                    memory: "90Mi"        
              ports:  
                - name: http
                  containerPort: 80
                  protocol: TCP
    selector:
          app: apprc