apiVersion: v1
kind: Service
metadata:
  name: student
spec:
  type: ClusterIP
  selector:
    app: student
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: student