apiVersion: v1
kind: Service
metadata:
  name: employee
spec:
  type: ClusterIP
  selector:
    app: employee
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: employee