apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: 
    http:
      paths:
        
         -  path: /
            pathType: Prefix
            backend:
              service: 
                name: todo
                port:
                  number: 80
         -  path: /student
            pathType: Prefix
            backend:
              service: 
                name: student
                port:
                  number: 8080
         -  path: /employee
            pathType: Prefix
            backend:
              service: 
                name: employee
                port:
                  number: 3000