apiVersion: v1
kind: Service
metadata:
  name: student
  namespace: mytodonamespace
spec:
  type: LoadBalancer
  selector:
    app: student
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: student