apiVersion: v1
kind: Service
metadata:
  name: todo
  namespace: todo
spec:
  type: LoadBalancer
  selector:
    app: todo
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: todo
