apiVersion: v1
kind: Pod
metadata: 
  name: mytodoapp
  namespace: mytodonamespace
  labels:
    app: mytodoapp
spec: 
  containers: 
    - name: todo
      image: rahuluencha/todo
      ports:  
        - containerPort: 80
          protocol: TCP 
---
apiVersion: v1
kind: Service
metadata:
  name: my-service1
  namespace: mytodonamespace
spec:
  type: LoadBalancer
  selector:
    app: mytodoapp
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: todo
