apiVersion: apps/v1 
kind: DaemonSet 
metadata:
        name: daemonset
        labels: 
              app: daemonset
spec:
     selector:
           matchLabels:
                app: daemonset    
     template:
          metadata:  #like a tag
              labels: 
                  app: daemonset 
          spec:
            containers:
                - name: mypod-cont1
                  image: nginx:latest
                  resources: 
                      requests:
                        cpu: "50m"
                        memory: "90Mi"        
                  ports:  
                    - name: http
                      containerPort: 80
                      protocol: TCP            