apiVersion: apps/v1
kind:  ReplicaSet
metadata: 
       name: myreplica4
       labels:
            app: myreplica4
spec: 
    replicas: 2  #how many replica's you want to create on the basis of template
    template:
      metadata:  #like a tag
         labels: 
            app: myreplica4
      spec:
        containers:
            - name: mypod-cont1
              image: nginx:latest
              resources: 
                  requests:
                    cpu: "50m"
                    memory: "90Mi"        
              ports:  
                - name: http
                  containerPort: 80
                  protocol: TCP
    selector: 
         matchExpressions: 
            - {key: app, operator: NotIn, values: [webappreplica, webappreplica2]}